version: '3.2'

services:
#____________________________________________________________________________________________
# Pure FTPD Stack

  # UbiquiTi Controller Software 
  Pure_FTP:
    image: vimagick/pure-ftpd
#---------------------------------------------------------------
    volumes:  
    - type: volume
      source: bennetnas_ftp_home
      target: /home/ftpuser
      volume:
        nocopy: true
#---------------------------------------------------------------
    volumes:  
    - type: volume
      source: bennetnas_ftp_data
      target: /etc/pure-ftpd
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - FTP_Network
#---------------------------------------------------------------
    ports:
    - 21:21/tcp


#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Networks

networks:

  FTP_Network:
    driver: overlay
    attachable: true


#____________________________________________________________________________________________________________________________________________________________________________________________________________
# Network Volume Mappings (NFS)

volumes:

#FTP Stack Persistant Data NFS Volumes (On BenNetNAS)

  bennetnas_ftp_home:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/FTP-Stack/ftp_home/ftpuser"
#-------------------------------------------------------------
  bennetnas_ftp_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/FTP-Stack/ftp_data"
  
