version: '3.2'

services:
#__________________________________________________________________________________
# Pure FTP Stack

# Pure FTP

  Pure_FTP:
    image: stilliard/pure-ftpd
#---------------------------------------------------------------
    networks:
      - FTP_Network
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_ftp_config
      target: /etc/pure-ftpd/passwd
      volume:
        nocopy: true
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_ftp_home
      target: /home
      volume:
        nocopy: true
#---------------------------------------------------------------
    ports:
    - 21:21/tcp
    - 21:21/udp
    - 11000-11009:11000-11009/tcp
    - 11000-11009:11000-11009/udp
    environment:
      PUBLICHOST: "192.168.8.150"
      FTP_PASSIVE_PORTS: 11000:11009
      --expose: 11000-11009



#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Networks

networks:

  FTP_Network: 
    driver: overlay
    attachable: true

#____________________________________________________________________________________________________________________________________________________________________________________________________________
# Network Volume Mappings (NFS)

volumes:

#-----------------------------------------------------------------------------------------------  

# FTP Stack Persistant Data NFS Volumes (On BenNetNAS)

  bennetnas_ftp_config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Guac-Stack/ftp_data"
#-----------------------------------------
  bennetnas_ftp_home:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/FTP-Stack/ftp_home"
#-----------------------------------------


#------------------------------------------------------------------------------------------------    
