version: '3.2'

services:
#__________________________________________________________________________________
# Guacamole Stack

# Guacamole Deamon

  Guacamole_Deamon:
    image: guacamole/guacd
    networks:
      - Guacamole_Network
    volumes:
    - type: volume
      source: bennetnas_guacd_drive
      target: /drive
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_guacd_record
      target: /record
      volume:
        nocopy: true

#-----------------------------------------------------------------------------------------
  # Guac postgres SQL Database 

  Guac_Postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: guacamole_user
    image: postgres
    networks:
      - Guacamole_Network
    volumes:
    - type: volume
      source: bennetnas_guac_sql_init
      target: /docker-entrypoint-initdb.d
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_guac_sql_data
      target: /var/lib/postgresql/data
      volume:
        nocopy: true

#--------------------------------------------------------------------------------------------
  # Gaucamole Webserver

  Guacamole_Webserver:
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: Guac_Postgres
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    networks:
      - Guacamole_Network
    ports:
    - 8007:8080/tcp

#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Networks

networks:

  Guacamole_Network:
    driver: overlay
    attachable: true

#____________________________________________________________________________________________________________________________________________________________________________________________________________
# Network Volume Mappings (NFS)

volumes:

#-----------------------------------------------------------------------------------------------  

# Guacamole Stack Persistant Data NFS Volumes (On BenNetNAS)

  bennetnas_guacd_drive:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guacd_drive"
#-----------------------------------------
  bennetnas_guacd_record:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guacd_record"
#-----------------------------------------
  bennetnas_guac_sql_init:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guac_sql_init"
#-----------------------------------------
  bennetnas_guac_sql_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guac_sql_data"

#------------------------------------------------------------------------------------------------    
