version: '3.7'

services:
#__________________________________________________________________________________
# Guacamole Stack

# Guacamole Deamon

  Guacamole:
    image: oznu/guacamole
#---------------------------------------------------------------
    networks:
      - Guacamole_Network
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_guacd_config
      target: /config
      volume:
        nocopy: true
#---------------------------------------------------------------
    ports:
    - 8007:8080/tcp
#---------------------------------------------------------------
# Health Checks still need work
    healthcheck:
     test: curl --fail -s http://localhost:8080/ || exit 1
     interval: 1m30s
     timeout: 30s
     start_period: 2m
     retries: 3 

#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Networks

networks:

  Guacamole_Network:
    driver: overlay
    attachable: true

#____________________________________________________________________________________________________________________________________________________________________________________________________________
# Network Volume Mappings (NFS)

volumes:

#-----------------------------------------------------------------------------------------------  

# Guacamole Stack Persistant Data NFS Volumes (On BenNetNAS)

  bennetnas_guacd_config:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Guac-Stack/guac_data"
#-----------------------------------------


#------------------------------------------------------------------------------------------------    
