version: '3.2'

services:
#__________________________________________________________________________________
# Torrent Stack

    # Deluge Torrent Client
  Deluge:
    image: linuxserver/deluge
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_deluge
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
    networks:
      - Torrent_Network
    ports:
    - 8001:8112/tcp
    - 8002:58846/tcp

#----------------------------------------------------------------------------------
  # Sonarr NZB Manager for TV Shows

  Sonarr:
    image: linuxserver/sonarr
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_sonarr
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_tv
      target: /tv
      volume:
        nocopy: true
    networks:
      - Torrent_Network
    ports:
    - 8003:8989/tcp

#--------------------------------------------------------------------------------------------
  # Sonarr NZB Manager for Movies

  Radarr:
    image: linuxserver/radarr
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_radarr
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_movies
      target: /movies
      volume:
        nocopy: true
    networks:
      - Torrent_Network
    ports:
    - 8004:7878/tcp

#--------------------------------------------------------------------------------------------
  # Sonarr NZB Manager for Movies

  Lidarr:
    image: linuxserver/lidarr
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_lidarr
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_music
      target: /music
      volume:
        nocopy: true
    networks:
      - Torrent_Network
    ports:
    - 8005:8686/tcp

#--------------------------------------------------------------------------------------------
  # Jackett Torret Site Proxy Service

  Jackett:
    image: linuxserver/jackett
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_jacket_data
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_jacket_downloads
      target: /downloads
      volume:
        nocopy: true
    networks:
      - Torrent_Network
    ports:
    - 8006:9117/tcp

#__________________________________________________________________________________
# Guac Stack

# Guacamole Deamon

  Guacamole_Deamon:
    image: guacamole/guacd
    networks:
      - Guacamole_Network
    volumes:
    - type: volume
      source: bennetnas_guacd_drive
      target: /drive
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_guacd_record
      target: /record
      volume:
        nocopy: true

#-----------------------------------------------------------------------------------------
  # Guac postgres SQL Database 

  Guac_Postgres:
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: guacamole_user
    image: postgres
    networks:
      - Guacamole_Network
    volumes:
    - type: volume
      source: bennetnas_guac_sql_init
      target: /docker-entrypoint-initdb.d
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_guac_sql_data
      target: /var/lib/postgresql/data
      volume:
        nocopy: true

#--------------------------------------------------------------------------------------------
  # Gaucamole Webserver

  Guacamole_Webserver:
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    networks:
      - Guacamole_Network
    ports:
    - 8007:8080/tcp

#____________________________________________________________________________________________
# Unifi Stack

  # UbiquiTi Controller Software 
  Unifi_Controller:
    image: linuxserver/unifi
    environment:
      PUID: 1000
      GUID: 1000
    volumes:  
    - type: volume
      source: bennetnas_unifi_data
      target: /config
      volume:
        nocopy: true
    networks:
      - Unifi_Network
    ports:
    - 443:443/tcp
    - 443:443/udp
    - 3478:3478/udp
    - 3478:3478/tcp
    - 8883:8883/tcp
    - 10001:10001/udp
    - 8080:8080/tcp
    - 8081:8081/tcp
    - 8443:8443/tcp
    - 8880:8880/tcp
    - 6789:6789/tcp

#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Networks

networks:
#--------------------------
  Torrent_Network:
    driver: overlay
    attachable: true
#--------------------------
  Guacamole_Network:
    driver: overlay
    attachable: true
#--------------------------
  Unifi_Network:
    driver: overlay
    attachable: true
#--------------------------
  Portainer_Network:
    driver: overlay
    attachable: true

#____________________________________________________________________________________________________________________________________________________________________________________________________________
# Network Volume Mappings (NFS)

volumes:

#--------------------------------

# BenNetNAS Media Volumes

  bennetnas_downloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Downloads"
#--------------------------------
  bennetnas_tv:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/TV"
#--------------------------------      
  bennetnas_movies:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/Movies"
#--------------------------------      
  bennetnas_music:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/Music"

#---------------------------------------------------------------------------------------------  

# Torrent Stack Persistant Data NFS Volumes (On BenNetNAS) 

  bennetnas_deluge:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/deluge_data"
#-----------------------------------------
  bennetnas_sonarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/sonarr_data"
#-----------------------------------------
  bennetnas_radarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/radarr_data"
#-----------------------------------------
  bennetnas_jacket_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/jacket_data"
#-----------------------------------------
  bennetnas_jacket_downloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/jacket_data/downloads"
#-----------------------------------------
  bennetnas_lidarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/lidarr_data"

#-----------------------------------------------------------------------------------------------  

# Guacamole Stack Persistant Data NFS Volumes (On BenNetNAS)

  bennetnas_guacd_drive:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guacd_drive"
#-----------------------------------------
  bennetnas_guacd_record:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guacd_record"
#-----------------------------------------
  bennetnas_guac_sql_init:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guac_sql_init"
#-----------------------------------------
  bennetnas_guac_sql_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/guac_data/guac_sql_data"

#------------------------------------------------------------------------------------------------    

#Unifi Stack Persistant Data NFS Volumes (On BenNetNAS)

  bennetnas_unifi_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/unifi_data"

#------------------------------------------
  bennetnas_portainer_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/portainer_data"
#-------------------------------------------------------------------------------------------------
  
