version: '3.7'

services:
#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Torrent Stack
# All Containers related to bit torrent

#_____________________________________________________________________________________________
    # Deluge Torrent Client
  Deluge:
    image: linuxserver/deluge
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_deluge
      target: /config
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8001:8112/tcp
    - 8002:58846/tcp
#---------------------------------------------------------------
# Health Checks still need work
    healthcheck:
     test: CMD curl --fail -s http://192.168.8.150:8001/ || exit 1
     interval: 1m30s
     timeout: 30s
     retries: 10
     start_period: 40s
#_____________________________________________________________________________________________
  # Sonarr NZB Manager for TV Shows

  Sonarr:
    image: linuxserver/sonarr
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_sonarr
      target: /config
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_tv
      target: /tv
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8003:8989/tcp
#---------------------------------------------------------------
# Health Checks still need work
#    healthcheck:
#     test: curl --fail -s http://192.168.8.150:8003/ || exit 1
#      interval: 1m30s
#      timeout: 10s
#      retries: 3

#_____________________________________________________________________________________________
  # Radarr NZB Manager for Movies

  Radarr:
    image: linuxserver/radarr
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_radarr
      target: /config
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_movies
      target: /movies
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8004:7878/tcp

#_____________________________________________________________________________________________
  # Muximux NZB web front end for Torrent Services

  Muximux:
    image: linuxserver/muximux
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_muximux
      target: /config
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8008:80/tcp

#_____________________________________________________________________________________________
  # Lidarr NZB Manager for Music

  Lidarr:
    image: linuxserver/lidarr
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_lidarr
      target: /config
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_music
      target: /music
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8005:8686/tcp

#_____________________________________________________________________________________________
  # Jackett Torrent Site Proxy Service

  Jackett:
    image: linuxserver/jackett
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_jacket
      target: /config
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_jacket_downloads
      target: /downloads
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8006:9117/tcp

#_____________________________________________________________________________________________
  # Filebot file manipulation software.

  Filebot:
    image: jlesage/filebot
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_filebot
      target: /config
      volume:
        nocopy: true
#-----------------------------------------
    - type: volume
      source: bennetnas_downloads
      target: /storage
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8009:5800/tcp
#_____________________________________________________________________________________________
  # Organizr Web interface front end organizer

  Organizr:
    image: linuxserver/organizr
#---------------------------------------------------------------
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
#---------------------------------------------------------------
    volumes:
    - type: volume
      source: bennetnas_organizr
      target: /config
      volume:
        nocopy: true
#---------------------------------------------------------------
    networks:
      - Torrent_Network
#---------------------------------------------------------------
    ports:
    - 8010:80/tcp

#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Networks

networks:
#--------------------------
  Torrent_Network:
    driver: overlay
    attachable: true

#____________________________________________________________________________________________________________________________________________________________________________________________________________
# Network Volume Mappings (NFS)

volumes:

#--------------------------------------------------------------------------------------------- 

# BenNetNAS Media Volumes

  bennetnas_downloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Downloads"
#--------------------------------
  bennetnas_tv:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/TV"
#--------------------------------      
  bennetnas_movies:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/Movies"
#--------------------------------      
  bennetnas_music:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/Music"

#---------------------------------------------------------------------------------------------  

# Torrent Stack Persistant Data NFS Volumes (On BenNetNAS) 

  bennetnas_deluge:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/deluge_data"
#-----------------------------------------
  bennetnas_sonarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/sonarr_data"
#-----------------------------------------
  bennetnas_radarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/radarr_data"
#-----------------------------------------
  bennetnas_jacket:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/jacket_data"
#-----------------------------------------
  bennetnas_jacket_downloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/jacket_data/downloads"
#-----------------------------------------
  bennetnas_lidarr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/lidarr_data"
#-----------------------------------------
  bennetnas_muximux:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/muximux_data"
#-----------------------------------------
  bennetnas_filebot:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/filebot_data"
#-----------------------------------------
  bennetnas_organizr:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/DEV/Tor-Stack/organizr_data"

#-----------------------------------------------------------------------------------------------  
  
