version: '3.2'

services:
#____________________________________________________________________________________________
# Unifi Stack

  # UbiquiTi Controller Software 
  Unifi_Controller:
    image: linuxserver/unifi
    environment:
      PUID: 1000
      GUID: 1000
    volumes:  
    - type: volume
      source: bennetnas_unifi_data
      target: /config
      volume:
        nocopy: true
    networks:
      - Unifi_Network
    ports:
    - 443:443/tcp
    - 443:443/udp
    - 3478:3478/udp
    - 3478:3478/tcp
    - 8883:8883/tcp
    - 10001:10001/udp
    - 8080:8080/tcp
    - 8081:8081/tcp
    - 8443:8443/tcp
    - 8880:8880/tcp
    - 6789:6789/tcp

#___________________________________________________________________________________________________________________________________________________________________________________________________________
# Networks

networks:

  Unifi_Network:
    driver: overlay
    attachable: true
    internal: true 
    external: true


#____________________________________________________________________________________________________________________________________________________________________________________________________________
# Network Volume Mappings (NFS)

volumes:

#Unifi Stack Persistant Data NFS Volumes (On BenNetNAS)

  bennetnas_unifi_data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/unifi_data"
  
