version: '3.2'
# containers
services:

  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: vaultuser
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: vaultdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaultdb"]
      interval: 2s
      timeout: 3s
      retries: 30

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 2s
      timeout: 3s
      retries: 30

  vault:
    container_name: vault
    image: vault
    ports:
      - "8201:8200"
    volumes:
      - ./vault/:/vault/config
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
      SKIP_SETCAP: 1
    links:
      - postgres
      - rabbit
    command: ["/vault/config/config.sh"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 2s
      timeout: 3s
      retries: 30