version: '3.2'
# containers
services:
##########################################################################################
  # Portainer Docker GUI 
  portainer:
    container_name: Portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock    
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: bennetnas_portainer_data
        target: /data
        volume:
          nocopy: true
    network_mode: bridge
    ports:
    - 9000:9000/tcp
##########################################################################################
# NextCloud Stack
  nextcloud:  
    container_name: NextCloud      
    image: nextcloud
    ports:
    - 8015:80
    links:
    - nextcloud-db
    volumes:
      - type: volume
        source: bennetnas_nextcloud_data
        target: /var/www/html
        volume:
          nocopy: true
    restart: always
    networks:
      nextcloud:
##################################################
  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - type: volume
        source: bennetnas_nextcloud-db_data
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_ROOT_PASSWORD=qwe123
      - MYSQL_PASSWORD=qwe123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      nextcloud:
##########################################################################################
# Torrent Stack
  # Deluge Torrent Client
  deluge:
    container_name: Deluge
    image: linuxserver/deluge
    restart: always
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
      - type: volume
        source: bennetnas_deluge_data
        target: /config
        volume:
          nocopy: true
      - type: volume
        source: bennetnas_downloads
        target: /downloads
        volume:
          nocopy: true
    networks:
      tor:
    ports:
    - 8001:8112/tcp
    - 8002:58846/tcp
##################################################
  # Sonarr NZB Manager for TV Shows
  sonarr:
    container_name: Sonarr
    image: linuxserver/sonarr
    restart: always
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_sonarr_data
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_tv
      target: /tv
      volume:
        nocopy: true
    networks:
      tor:
    ports:
    - 8003:8989/tcp
##################################################
  # Radarr NZB Manager for Movies
  radarr:
    container_name: Radarr
    image: linuxserver/radarr
    restart: always
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_radarr_data
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_movies
      target: /movies
      volume:
        nocopy: true
    networks:
      tor:
    ports:
    - 8004:7878/tcp
##################################################
  # Lidarr NZB Manager for Music
  Lidarr:
    container_name: Lidarr
    image: linuxserver/lidarr
    restart: always
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_lidarr_data
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_downloads
      target: /downloads
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_music
      target: /music
      volume:
        nocopy: true
    networks:
      tor:
    ports:
    - 8005:8686/tcp
##################################################
  # Jackett Torret Site Proxy Service
  jackett:
    container_name: Jackett
    image: linuxserver/jackett
    restart: always
    environment:
      PUID: 1000
      GUID: 1000
      TZ: EST
    volumes:
    - type: volume
      source: bennetnas_jacket_data
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_jacket_downloads
      target: /downloads
      volume:
        nocopy: true
    networks:
      tor:
    ports:
    - 8006:9117/tcp
##########################################################################################
# Guacamole RDP Stack
  # Guacamole Deamon
  guacd:
    container_name: Guacamole_Daemon
    image: guacamole/guacd
    networks:
      guac:
    restart: always
    volumes:
    - type: volume
      source: bennetnas_guacd_drive
      target: /drive
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_guacd_record
      target: /record
      volume:
        nocopy: true
##################################################    
  # Guac postgres SQL Database 
  postgres:
    container_name: Guacamole_Postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: guacamole_user
    image: postgres
    networks:
      guac:
    restart: always
    volumes:
    - type: volume
      source: bennetnas_guac_sql_init
      target: /docker-entrypoint-initdb.d
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_guac_sql_data
      target: /var/lib/postgresql/data
      volume:
        nocopy: true
################################################## 
  # Gaucamole Webserver
  guacamole:
    container_name: Guacamole_Webserver
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guac:
    restart: always
    ports:
    - 8007:8080/tcp
##########################################################################################
# Plex Stack
  Plex_Server: 
    container_name: Plex
    image: linuxserver/plex
    restart: always
    environment:
      PUID: 1000
      GUID: 1000
    volumes:
    - type: volume
      source: bennetnas_plex_data
      target: /config
      volume:
        nocopy: true
#    - type: volume
#      source: bennetnas_plex_transcode
#      target: /transcode
#      volume:
#        nocopy: true
#    - type: volume
#      source: bennetnas_downloads
#      target: /downloads
#      volume:
#        nocopy: true
    - type: volume
      source: bennetnas_tv
      target: /tv
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_movies
      target: /movies
      volume:
        nocopy: true
    networks:
      plex:
    ports:
    - 32400:32400/tcp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
################################################## 
# Ombi Media Requests 
  Ombi_Server:
    container_name: Ombi
    image: linuxserver/ombi
    restart: always
    environment:
      PUID: 1000
      GUID: 1000
      TZ:   EST
    volumes:
      - type: volume
        source: bennetnas_ombi_data
        target: /config
        volume:
          nocopy: true
      - type: volume
        source: bennetnas_ombi_shared
        target: /shared
        volume:
          nocopy: true
    networks:
      plex:
    ports:
    - 8011:3579/tcp
################################################## 
# PlexPy Media Requests 
  PlexPy_Server:
    container_name: PlexPy
    image: linuxserver/tautulli
    restart: always
    environment:
      PUID: 1000
      GUID: 0
      TZ:   EST
    volumes:  
    - type: volume
      source: bennetnas_plexpy_data
      target: /config
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_plexpy_logs
      target: /logs
      volume:
        nocopy: true
    - type: volume
      source: bennetnas_plexpy_shared
      target: /shared
      volume:
        nocopy: true
    networks:
      plex:
    ports:
    - 8012:8181/tcp
###########################################################################################################################
#Network for Guacamole Stack to communicate
networks:
  tor:
    driver: bridge
  guac:
    driver: bridge
  plex:
    driver: bridge
  nextcloud:
    driver: bridge
###########################################################################################################################
#NFS mapped volumes to bennetnas
volumes:

#################################################
# BenNetNas Media 
  bennetnas_downloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Downloads"
  bennetnas_tv:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/TV"
  bennetnas_movies:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/Movies"
  bennetnas_music:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media/Music"
  bennetnas_media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Media"

#################################################
# BenNetNas Docker persistant data Volumes

###############################
  bennetnas_portainer_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Portainer/portainer_data"
###############################
  bennetnas_nextcloud_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/NextCloud/DB/nextcloud-db_data"
  bennetnas_nextcloud-db_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/NextCloud/App/nextcloud_data"  
###############################
  bennetnas_deluge_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Torrent/Deluge/deluge_data"
  bennetnas_sonarr_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Torrent/Sonarr/sonarr_data"
  bennetnas_radarr_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Torrent/Radarr/radarr_data"
  bennetnas_jacket_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Torrent/Jacket/jacket_data"
  bennetnas_jacket_downloads:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Torrent/Jacket/downloads"
  bennetnas_lidarr_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Torrent/Lidarr/lidarr_data"
###############################
  bennetnas_guacd_drive:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Guacamole/guacd_drive"
  bennetnas_guacd_record:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Guacamole/guacd_record"

  bennetnas_guac_sql_init:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Guacamole/guac_sql_init"
  bennetnas_guac_sql_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Guacamole/guac_sql_data"
###############################
  bennetnas_plex_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Plex/plex_data"
  bennetnas_plex_transcode:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Plex/plex_transcode"

  bennetnas_ombi_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Plex/ombi_data"
  bennetnas_ombi_shared:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Plex/ombi_shared"

  bennetnas_plexpy_data:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Plex/plexpy_data"
  bennetnas_plexpy_logs:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Plex/plexpy_logs"
  bennetnas_plexpy_shared:
    driver_opts:
      type: "nfs4"
      o: "addr=192.168.10.120,nolock,soft,rw"
      device: ":/volume1/Docker/PROD/BenNetDock/Plex/plexpy_shared"


